CLASS zcl_767890_demo01 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_767890_demo01 IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    DATA travels TYPE TABLE OF /DMO/I_Travel_D.

    SELECT FROM /DMO/I_Travel_D
      FIELDS * WHERE TRAVELID = '00000001'
      INTO TABLE @travels.

    out->write( travels ).

  ENDMETHOD.
ENDCLASS.
